// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: childs.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createChild = `-- name: CreateChild :execresult
INSERT INTO childs (` + "`" + `name` + "`" + `, ` + "`" + `birthday` + "`" + `, ` + "`" + `nickname` + "`" + `) VALUES (
    ?, ?, ? 
)
`

type CreateChildParams struct {
	Name     string
	Birthday time.Time
	Nickname sql.NullString
}

func (q *Queries) CreateChild(ctx context.Context, arg CreateChildParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChild, arg.Name, arg.Birthday, arg.Nickname)
}

const deleteChild = `-- name: DeleteChild :exec
DELETE FROM childs WHERE id = ?
`

func (q *Queries) DeleteChild(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteChild, id)
	return err
}

const listChilds = `-- name: ListChilds :many
SELECT id, name, birthday, nickname FROM childs
`

func (q *Queries) ListChilds(ctx context.Context) ([]Child, error) {
	rows, err := q.db.QueryContext(ctx, listChilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Child
	for rows.Next() {
		var i Child
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Birthday,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
