// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type Child struct {
	ID       int32
	Name     string
	Birthday time.Time
	Nickname sql.NullString
}
